#### Social_Network_Ads ML Exercise

1) Read the dataset 'Social_Network_Ads.csv'<br>
2) Remove/handle null values<br>
3) Considering 'Age' and 'Estimated Salary' as input features and 'Purchased' as output feature, generate the following models after splitting the dataset into training and test dataset with test_size as 25%.<br>
a) Logistic Regression <br>
b) Decision Tree <br>
c) RandomForest <br>
d) KNN<br>
and predict the Purchased class label.<br>
4) Generate confusion matrix and classification report for each of these models.<br> 
5) Compute Accuracy score for each of these models.<br>
6) Scale the input features using feature Scaling and then repeat question 3, 4 and 5<br>

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df=pd.read_csv('D:\PYTHON ALL/Social_Network_Ads.csv')

In [14]:
df.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [15]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [18]:
df['Gender'] = df['Gender'].replace({'Male':0,'Female':1})

In [19]:
df.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       0   19            19000          0
1  15810944       0   35            20000          0
2  15668575       1   26            43000          0
3  15603246       1   27            57000          0
4  15804002       0   19            76000          0

In [25]:
x=df.iloc[:,2:-1]
y=df.iloc[:,-1]

In [26]:
x

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [27]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

### a) Logistic Regression

In [43]:
from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [44]:
print(lr.score(x_test,y_test))

0.64


In [45]:
lr_pred=lr.predict(x_test)

In [46]:
lr_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [47]:
from sklearn.metrics import confusion_matrix,classification_report

In [48]:
print(confusion_matrix(y_test,lr_pred))

[[64  0]
 [36  0]]


In [49]:
print(classification_report(y_test,lr_pred))

              precision    recall  f1-score   support

           0       0.64      1.00      0.78        64
           1       0.00      0.00      0.00        36

    accuracy                           0.64       100
   macro avg       0.32      0.50      0.39       100
weighted avg       0.41      0.64      0.50       100



D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [51]:
m=lr.coef_

In [52]:
m

array([[-2.39308278e-09, -2.57645797e-06]])

In [53]:
b=lr.intercept_

In [54]:
b

array([-2.30551041e-10])

### b) Decision Tree

In [55]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
dt=DecisionTreeClassifier()

In [57]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [58]:
print(dt.score(x_test,y_test))

0.83


In [59]:
dt_pred=dt.predict(x_test)

In [60]:
dt_pred[:10]

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [75]:
from sklearn.metrics import confusion_matrix, classification_report

In [76]:
print(confusion_matrix(y_test,dt_pred))

[[54 10]
 [ 7 29]]


In [77]:
print(classification_report(y_test,dt_pred))

              precision    recall  f1-score   support

           0       0.89      0.84      0.86        64
           1       0.74      0.81      0.77        36

    accuracy                           0.83       100
   macro avg       0.81      0.82      0.82       100
weighted avg       0.83      0.83      0.83       100



### c) Random Forest

In [63]:
from sklearn.ensemble import RandomForestClassifier

In [64]:
rf=RandomForestClassifier()

In [65]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [66]:
print(rf.score(x_test,y_test))

0.9


In [67]:
rf_pred=rf.predict(x_test)

In [69]:
rf_pred[:10]

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [72]:
from sklearn.metrics import confusion_matrix, classification_report

In [73]:
print(confusion_matrix(y_test,rf_pred))

[[56  8]
 [ 2 34]]


In [74]:
print(classification_report(y_test,rf_pred))

              precision    recall  f1-score   support

           0       0.97      0.88      0.92        64
           1       0.81      0.94      0.87        36

    accuracy                           0.90       100
   macro avg       0.89      0.91      0.89       100
weighted avg       0.91      0.90      0.90       100



### d) KNN - K-nearest Neighbors

In [81]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

In [88]:
knn=KNeighborsClassifier(n_neighbors=15)

In [89]:
knr=KNeighborsRegressor()

In [90]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [92]:
print(knn.score(x_test,y_test))

0.78


In [93]:
knn_pred=knn.predict(x_test)

In [94]:
knn_pred[:10]

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0], dtype=int64)

In [95]:
from sklearn.metrics import confusion_matrix, classification_report

In [96]:
print(confusion_matrix(y_test,knn_pred))

[[56  8]
 [14 22]]


In [97]:
print(classification_report(y_test,knn_pred))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84        64
           1       0.73      0.61      0.67        36

    accuracy                           0.78       100
   macro avg       0.77      0.74      0.75       100
weighted avg       0.78      0.78      0.77       100



### Scale the input features using feature Scaling 

In [100]:
from sklearn.model_selection import cross_val_score

### DecisionTree

In [99]:
criterion=['gini','entropy']

for i in criterion:
    score=cross_val_score(DecisionTreeClassifier(criterion=i),x,y)
    print(f'At {i},accuracy is {score.mean()}')
    print('At',i,",accuracy score is",score.mean())

At gini,accuracy is 0.8025
At gini ,accuracy score is 0.8025
At entropy,accuracy is 0.8074999999999999
At entropy ,accuracy score is 0.8074999999999999


In [102]:
mss=(2,3,4,5,6,7,8,9,10)
for i in mss:
    score=cross_val_score(DecisionTreeClassifier(min_samples_split=i),x,y)
    print(f'At min_samples_split {i},accuracy score is {score.mean()}')

At min_samples_split 2,accuracy score is 0.8099999999999999
At min_samples_split 3,accuracy score is 0.805
At min_samples_split 4,accuracy score is 0.8025
At min_samples_split 5,accuracy score is 0.8099999999999999
At min_samples_split 6,accuracy score is 0.8174999999999999
At min_samples_split 7,accuracy score is 0.8200000000000001
At min_samples_split 8,accuracy score is 0.825
At min_samples_split 9,accuracy score is 0.825
At min_samples_split 10,accuracy score is 0.8200000000000001


In [103]:
max_depth=(2,3,4,5,6,7,8,9)
for i in max_depth:
    score=cross_val_score(DecisionTreeClassifier(max_depth=i),x,y)
    print(f'At max_depth {i},accuracy score is {score.mean()}')

At max_depth 2,accuracy score is 0.8875
At max_depth 3,accuracy score is 0.845
At max_depth 4,accuracy score is 0.8274999999999999
At max_depth 5,accuracy score is 0.8525
At max_depth 6,accuracy score is 0.8275
At max_depth 7,accuracy score is 0.8150000000000001
At max_depth 8,accuracy score is 0.805
At max_depth 9,accuracy score is 0.8075000000000001


In [105]:
dt2=DecisionTreeClassifier(criterion='entropy',min_samples_split=8,max_depth=2)
dt2.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=2, min_samples_split=8)

In [106]:
print(dt2.score(x_test,y_test))

0.89


In [108]:
dt2_pred=dt2.predict(x_test)

In [110]:
dt2_pred[:10]

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [112]:
print(confusion_matrix(y_test,dt2_pred))

[[55  9]
 [ 2 34]]


In [111]:
print(classification_report(y_test,dt2_pred))

              precision    recall  f1-score   support

           0       0.96      0.86      0.91        64
           1       0.79      0.94      0.86        36

    accuracy                           0.89       100
   macro avg       0.88      0.90      0.88       100
weighted avg       0.90      0.89      0.89       100



### Random Forest

In [118]:
bootstrap=[True,False]
for i in bootstrap:
    scores=cross_val_score(RandomForestClassifier(bootstrap=i),x,y)
    print(f'At bootstrap {i},the score is {score.mean()}')

At bootstrap True,the score is 0.8425
At bootstrap False,the score is 0.8425


In [114]:
for i in range(2,20):
    score=cross_val_score(RandomForestClassifier(n_estimators=i),x,y)
    print(f'At n equals to {i},accuracy score is {score.mean()}')

At n equals to 2,accuracy score is 0.8550000000000001
At n equals to 3,accuracy score is 0.8549999999999999
At n equals to 4,accuracy score is 0.8275
At n equals to 5,accuracy score is 0.8324999999999999
At n equals to 6,accuracy score is 0.845
At n equals to 7,accuracy score is 0.8450000000000001
At n equals to 8,accuracy score is 0.8375
At n equals to 9,accuracy score is 0.8474999999999999
At n equals to 10,accuracy score is 0.8400000000000001
At n equals to 11,accuracy score is 0.85
At n equals to 12,accuracy score is 0.8400000000000001
At n equals to 13,accuracy score is 0.8525
At n equals to 14,accuracy score is 0.845
At n equals to 15,accuracy score is 0.8525
At n equals to 16,accuracy score is 0.8400000000000001
At n equals to 17,accuracy score is 0.86
At n equals to 18,accuracy score is 0.8625
At n equals to 19,accuracy score is 0.8425


In [115]:
for i  in range (2,20):
    mss=cross_val_score(RandomForestClassifier(min_samples_split=i),x,y)
    print(f'At min_samples_split {i},accuracy score is {mss.mean()}')

At min_samples_split 2,accuracy score is 0.8474999999999999
At min_samples_split 3,accuracy score is 0.8550000000000001
At min_samples_split 4,accuracy score is 0.86
At min_samples_split 5,accuracy score is 0.8674999999999999
At min_samples_split 6,accuracy score is 0.8674999999999999
At min_samples_split 7,accuracy score is 0.8675
At min_samples_split 8,accuracy score is 0.8649999999999999
At min_samples_split 9,accuracy score is 0.8699999999999999
At min_samples_split 10,accuracy score is 0.8699999999999999
At min_samples_split 11,accuracy score is 0.875
At min_samples_split 12,accuracy score is 0.8699999999999999
At min_samples_split 13,accuracy score is 0.8699999999999999
At min_samples_split 14,accuracy score is 0.8724999999999999
At min_samples_split 15,accuracy score is 0.8724999999999999
At min_samples_split 16,accuracy score is 0.8699999999999999
At min_samples_split 17,accuracy score is 0.8724999999999999
At min_samples_split 18,accuracy score is 0.875
At min_samples_split 19

In [116]:
for i  in range (2,20):
    max_depth=cross_val_score(RandomForestClassifier(max_depth=i),x,y)
    print(f'At max_depth {i},accuracy score is {max_depth.mean()}')

At max_depth 2,accuracy score is 0.8800000000000001
At max_depth 3,accuracy score is 0.8775000000000001
At max_depth 4,accuracy score is 0.8799999999999999
At max_depth 5,accuracy score is 0.8799999999999999
At max_depth 6,accuracy score is 0.8574999999999999
At max_depth 7,accuracy score is 0.8574999999999999
At max_depth 8,accuracy score is 0.8625
At max_depth 9,accuracy score is 0.8550000000000001
At max_depth 10,accuracy score is 0.85
At max_depth 11,accuracy score is 0.8525
At max_depth 12,accuracy score is 0.8550000000000001
At max_depth 13,accuracy score is 0.8574999999999999
At max_depth 14,accuracy score is 0.8525
At max_depth 15,accuracy score is 0.86
At max_depth 16,accuracy score is 0.8525
At max_depth 17,accuracy score is 0.86
At max_depth 18,accuracy score is 0.85
At max_depth 19,accuracy score is 0.8550000000000001


In [122]:
rf2=RandomForestClassifier(criterion='entropy',n_estimators=18,min_samples_split=11,max_depth=2)
rf2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=2, min_samples_split=11,
                       n_estimators=18)

In [123]:
print(rf2.score(x_test,y_test))

0.89


In [124]:
rf2_pred=rf2.predict(x_test)

In [125]:
rf2_pred[:10]

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [126]:
print(confusion_matrix(y_test,rf2_pred))

[[55  9]
 [ 2 34]]


In [127]:
print(classification_report(y_test,rf2_pred))

              precision    recall  f1-score   support

           0       0.96      0.86      0.91        64
           1       0.79      0.94      0.86        36

    accuracy                           0.89       100
   macro avg       0.88      0.90      0.88       100
weighted avg       0.90      0.89      0.89       100



### K-nearest Neighbors

In [130]:
for i in range(2,20):
    score=cross_val_score(KNeighborsClassifier(n_neighbors=i),x,y)
    print(f'At n_neighbors {i},accuracy score is {score.mean()}')

At n_neighbors 2,accuracy score is 0.755
At n_neighbors 3,accuracy score is 0.7625
At n_neighbors 4,accuracy score is 0.7699999999999999
At n_neighbors 5,accuracy score is 0.7674999999999998
At n_neighbors 6,accuracy score is 0.7625
At n_neighbors 7,accuracy score is 0.7675000000000001
At n_neighbors 8,accuracy score is 0.7725
At n_neighbors 9,accuracy score is 0.7699999999999999
At n_neighbors 10,accuracy score is 0.75
At n_neighbors 11,accuracy score is 0.7474999999999999
At n_neighbors 12,accuracy score is 0.7575
At n_neighbors 13,accuracy score is 0.7525000000000001
At n_neighbors 14,accuracy score is 0.7525000000000001
At n_neighbors 15,accuracy score is 0.7575
At n_neighbors 16,accuracy score is 0.7575
At n_neighbors 17,accuracy score is 0.7449999999999999
At n_neighbors 18,accuracy score is 0.7550000000000001
At n_neighbors 19,accuracy score is 0.7575


In [139]:
knn2=KNeighborsClassifier(n_neighbors=4)
knn2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [140]:
print(knn2.score(x_test,y_test))


0.79


In [143]:
knn2_pred=knn2.predict(x_test)

In [144]:
knn2_pred[:10]

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 0], dtype=int64)

In [145]:
print(confusion_matrix(y_test,knn2_pred))

[[58  6]
 [15 21]]


In [146]:
print(classification_report(y_test,knn2_pred))

              precision    recall  f1-score   support

           0       0.79      0.91      0.85        64
           1       0.78      0.58      0.67        36

    accuracy                           0.79       100
   macro avg       0.79      0.74      0.76       100
weighted avg       0.79      0.79      0.78       100

